name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      variable1_input:
        description: 'variable1'
        required: true
      variable2_input:
        description: 'Enter a value for variable2'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Inputs as Environment Variables
      run: |
        echo "TF_VARIABLE1=${{ github.event.inputs.variable1_input }}" >> $GITHUB_ENV
        echo "TF_VARIABLE2=${{ github.event.inputs.variable2_input }}" >> $GITHUB_ENV

    # - name: Run Terraform
    #   run: |
    #     terraform init
    #     terraform apply -auto-approve \
    #       -var="variable1=${{ env.TF_VARIABLE1 }}" \
    #       -var="variable2=${{ env.TF_VARIABLE2 }}"
