name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      variable1_input:
        description: 'resource-group name'
        required: true
      variable2_input:
        description: 'location name'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Inputs as Environment Variables
      run: |
        echo "TF_VARIABLE1=${{ github.event.inputs.variable1_input }}" >> $GITHUB_ENV
        echo "TF_VARIABLE2=${{ github.event.inputs.variable2_input }}" >> $GITHUB_ENV

    - name: Run Terraform
      run: 
        terraform init
    
    - name: Terraform Plan
      run:
        terraform plan